server:
  port: 8081
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${issuer-uri}
  datasource:
    url: jdbc:postgresql://localhost:55000/postgres
    username: postgres
    password: postgrespw
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true

auth0:
  audience: my-admin-platform.com

app:
  jwt:
    issuer: 'map-auth-service'
    jwkPrivateKeyPKCS1: ${jwt-jwk-private-key}
    jwkPublicKeyX509Cert: ${jwt-jwk-public-key}